### PR TITLE
increased font size and switched to text area

### PR DESCRIPTION
**Pull request by RahalBhupathi**
I increased the font size of the word prompts from 'text-large' to 'text-4xl', and switched from using an input field for user input to a text area. Closes Issue #10.

Before:
image

After:
image

### CODE REVIEW

**Review by ashsajal1 — CHANGES_REQUESTED** [review]
Input element changes into textarea but its type isn't change. Chnage (e: ChangeEvent< HTMLInputElement >) into (e: ChangeEvent< HTMLTextAreaElement >)

**Comment by RahalBhupathi** [comment]
I changed the input type to TextArea, should be good to merge now

**Review by ashsajal1 — COMMENTED** [review]
Make text large in desktop and keep same in small screen. Thank you

**Comment by RahalBhupathi** [comment]
I added an event listener for the resize event on the window, it recalculates the font size based on the screen width whenever the window is resized. The 'baseFontSize' variable can be adjusted on line 21 to change the initial size of the prompt, it is currently 2xl. Please review and pull changes if no more adjustments are needed.

NVIDIA_Share_bEoPJnU40t

**Review by ashsajal1 — COMMENTED** [review]
You did great job. But it can be done easily by using 'md:text-2xl' tailwind css class.

**Comment by RahalBhupathi** [comment]
I updated the scaling to use tailwind css instead. Please review and pull changes.

**Pull request merged**
